### ISSUE TITLE
Updating to foundation 5?

### ISSUE THREAD

**Issue by conwaydev** [bauschan/generator-zurb-foundation#12]
Is anyone working on this?

**Comment by bauschan** [comment]
I have planed a separate repository for version 5:
https://github.com/bauschan/generator-foundation-five

hope to commit some basic stuff during the next days.

**Comment by conwaydev** [comment]
Ok awesome, looking forward to it

**Comment by chrisdl** [comment]
Nice! Also looking forwards to five!

**Comment by bauschan** [comment]
On 29.11.2013, at 23:31, Chris notifications@github.com wrote:

> Nice! Also looking forwards to five!
> 
> —
> Reply to this email directly or view it on GitHub.

Little Christmas present:

https://npmjs.org/package/generator-foundation-five

and on Github:
https://github.com/bauschan/generator-foundation-five

enjoy and as always any feedback is welcome
~Peter
